/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitelistRouteImport } from './routes/whitelist'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthDiscordRouteImport } from './routes/api/auth/discord'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord.callback'

const WhitelistRoute = WhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthDiscordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/rules': typeof RulesRoute
  '/whitelist': typeof WhitelistRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/rules': typeof RulesRoute
  '/whitelist': typeof WhitelistRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/rules': typeof RulesRoute
  '/whitelist': typeof WhitelistRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/discord'
    | '/rules'
    | '/whitelist'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/discord/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/discord'
    | '/rules'
    | '/whitelist'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/discord/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/discord'
    | '/rules'
    | '/whitelist'
    | '/api/auth/discord'
    | '/api/auth/logout'
    | '/api/auth/discord/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  DiscordRoute: typeof DiscordRoute
  RulesRoute: typeof RulesRoute
  WhitelistRoute: typeof WhitelistRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitelist': {
      id: '/whitelist'
      path: '/whitelist'
      fullPath: '/whitelist'
      preLoaderRoute: typeof WhitelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof ApiAuthDiscordRoute
    }
  }
}

interface ApiAuthDiscordRouteChildren {
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
}

const ApiAuthDiscordRouteChildren: ApiAuthDiscordRouteChildren = {
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
}

const ApiAuthDiscordRouteWithChildren = ApiAuthDiscordRoute._addFileChildren(
  ApiAuthDiscordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  DiscordRoute: DiscordRoute,
  RulesRoute: RulesRoute,
  WhitelistRoute: WhitelistRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
