/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitelistRouteImport } from './routes/whitelist'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhitelistRoute = WhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discord': typeof DiscordRoute
  '/rules': typeof RulesRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discord': typeof DiscordRoute
  '/rules': typeof RulesRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/discord': typeof DiscordRoute
  '/rules': typeof RulesRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/discord' | '/rules' | '/whitelist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/discord' | '/rules' | '/whitelist'
  id: '__root__' | '/' | '/about' | '/discord' | '/rules' | '/whitelist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DiscordRoute: typeof DiscordRoute
  RulesRoute: typeof RulesRoute
  WhitelistRoute: typeof WhitelistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitelist': {
      id: '/whitelist'
      path: '/whitelist'
      fullPath: '/whitelist'
      preLoaderRoute: typeof WhitelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DiscordRoute: DiscordRoute,
  RulesRoute: RulesRoute,
  WhitelistRoute: WhitelistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
